### ISSUE TITLE
ahocoder script files

### ISSUE THREAD

**Issue by malradhi** [santi-pdp/ahoproc_tools#6]
Dear Santi,

How could I view ahocoder/ahodecoder binary files in a way which can be easily read?
Thanks in advance and regards.

**Comment by santi-pdp** [comment]
I've found the issue now, didn't notice it before sorry. I dunno if you still need it, but for the record: The ahocoder binary files are just raw float32 concatenated, so you can read it like that. With Python you can make use of `struct.unpack()`, so that first you read the stream of bytes, let's say the `filename.lf0` file:
`bin_data = open('filename.lf0', 'rb').read()`

and then you read the total amount of float32 like:

`lf0 = struct.unpack('{}f'.format(len(bin_data) / 4), bin_data)`

**Comment by malradhi** [comment]
Thanks for reply. But are you sure you read ahocoder16/ahodecoder16 successfully?
For my side, I follow your comment but not works.

**Comment by santi-pdp** [comment]
Perhaps it's because of error in length specification of `struct.unpack` (must be int):

`lf0 = struct.unpack('{}f'.format(int(len(bin_data) / 4)), bin_data)`

**Comment by malradhi** [comment]
Off course, it's work for reading lf0 but not for ahocoder16/ahodecoder16.
Anyway, don't worry .. Thanks
